# Generated by Django 4.0.5 on 2022-06-16 17:00

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('vuln_backend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Artifacts',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('version', models.CharField(max_length=100)),
                ('purl', models.CharField(max_length=250, unique=True)),
                ('type', models.CharField(max_length=100)),
                ('cpes', models.JSONField()),
                ('licenses', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='ScanData',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('grype_scan', models.JSONField()),
                ('syft_scan', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='Statistics',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('number_dependencies', models.IntegerField()),
                ('number_vulnerabilities', models.IntegerField()),
                ('number_vuln_critical', models.IntegerField()),
                ('number_vuln_high', models.IntegerField()),
                ('number_vuln_medium', models.IntegerField()),
                ('number_vuln_low', models.IntegerField()),
                ('number_vuln_unknown', models.IntegerField()),
                ('scan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vuln_backend.scandata')),
            ],
        ),
        migrations.CreateModel(
            name='Vulnerabilities',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('vuln_id', models.CharField(max_length=100, unique=True)),
                ('severity', models.CharField(max_length=100)),
                ('cvss', models.JSONField()),
                ('fix', models.JSONField()),
                ('artifact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vuln_backend.artifacts')),
                ('scan', models.ManyToManyField(to='vuln_backend.scandata')),
            ],
        ),
        migrations.AlterField(
            model_name='repositories',
            name='url',
            field=models.URLField(unique=True),
        ),
        migrations.DeleteModel(
            name='ArtifactData',
        ),
        migrations.AddField(
            model_name='scandata',
            name='repository',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vuln_backend.repositories'),
        ),
        migrations.AddField(
            model_name='artifacts',
            name='scan',
            field=models.ManyToManyField(to='vuln_backend.scandata'),
        ),
        migrations.AlterUniqueTogether(
            name='artifacts',
            unique_together={('name', 'version')},
        ),
    ]
