# Generated by Django 4.0.5 on 2022-06-16 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vuln_backend', '0003_remove_vulnerabilities_artifact_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='statistics',
            name='number_vuln_negligible',
            field=models.IntegerField(default=None),
            preserve_default=False,
        ),
    ]
