# Generated by Django 4.0.5 on 2022-06-17 08:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('vuln_backend', '0004_statistics_number_vuln_negligible'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scandata',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
    ]
